### ISSUE TITLE
improvement: show quick fixes with ease instead of selecting type specifically

### ISSUE THREAD

**Issue by yildirayyorulmaz** [cem256/json-dynamic-widget-helper#12]
## Description

Currently, users need to select the type of quick fix they want to apply, which can be time-consuming and interrupt the coding flow. We should improve this process to make quick fixes more accessible and easier to use.

### Proposed Changes:

 When cursor on a json object, we can determine whether it contains a type or not.

**Comment by cem256** [comment]
Thanks for the suggestion!. This will definitely enhance the user experience. I will be implementing this improvement in the next release

**Comment by cem256** [comment]
@yildirayyorulmaz I pushed a new code that shows code actions when the line contains the word `"type"` instead of selecting the key `type` specifically.

**Comment by yildirayyorulmaz** [comment]
Thank you @cem256
